[package]
name = "near-api"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/near/near-api-rs"
homepage = "https://github.com/near/near-api-rs"
description = "Rust crate for interacting with the NEAR Protocol via RPC API"

[dependencies]
reqwest = { version = "0.11.4", features = ["json"] }

serde = "1.0.127"
serde_json = "1.0.66"

near-primitives = { git = "https://github.com/miraclx/nearcore", rev="be74434190ac20231c6f86599ee790c6e38724dd" }
near-jsonrpc-primitives = { git = "https://github.com/miraclx/nearcore", rev="be74434190ac20231c6f86599ee790c6e38724dd" }

[dev-dependencies]
tokio = { version = "1.1", features = ["rt", "macros"] }
